##
# @file
#
# Travis script for vli
#
# @author Tim Ewart
#

language: cpp
compiler:
  - clang
  - gcc
os:
  - linux
before_script:
  - sudo apt-get -qq update
  - sudo apt-get install libboost-all-dev cmake
  - sudo apt-get install software-properties-common
  - sudo apt-get install libgmp-dev
  - mkdir build
  - cd build
  - cmake -DVLI_TESTS=on ..
script:
  - make
  - make test
notifications:
  email:
    recipients:
      - timothee.ewart@gmail.com
    on_success: change
    on_failure: always
