/*
 *Very Large Integer Library, License - Version 1.0 - May 3rd, 2012
 *
 *Timothee Ewart - University of Geneva,
 *Andreas Hehn - Swiss Federal Institute of technology Zurich.
 *
 *Permission is hereby granted, free of charge, to any person or organization
 *obtaining a copy of the software and accompanying documentation covered by
 *this license (the "Software") to use, reproduce, display, distribute,
 *execute, and transmit the Software, and to prepare derivative works of the
 *Software, and to permit third-parties to whom the Software is furnished to
 *do so, all subject to the following:
 *
 *The copyright notices in the Software and this entire statement, including
 *the above license grant, this restriction and the following disclaimer,
 *must be included in all copies of the Software, in whole or in part, and
 *all derivative works of the Software, unless such copies or derivative
 *works are solely in the form of machine-executable object code generated by
 *a source language processor.
 *
 *THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 *IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 *FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 *SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 *FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 *ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 *DEALINGS IN THE SOFTWARE.
 */


#ifndef vli_inline_sub_h
#define vli_inline_sub_h

//SFINAE  http://www.boost.org/doc/libs/1_52_0/libs/utility/enable_if.html


//Address operand syntax, I always forget
//
//There are up to 4 parameters of an address operand that are presented in the syntax displacement(base register, offset register, scalar multiplier). This is equivalent to [base register + displacement + offset register * scalar multiplier] in Intel syntax. Either or both of the numeric, and either of the register parameters may be omitted:
//movl    -4(%ebp, %edx, 4), %eax  # Full example: load *(ebp - 4 + (edx * 4)) into eax
//movl    -4(%ebp), %eax           # Typical example: load a stack variable into eax
//movl    (%ecx), %edx             # No offset: copy the target of a pointer into a register
//leal    8(,%eax,4), %eax         # Arithmetic: multiply eax by 4 and add 8
//leal    (%eax,%eax,2), %eax      # Arithmetic: multiply eax by 2 and add eax (i.e. multiply by 3)

// "movq (%[y],%[counter],8), %[tmp_register]\n\t" load *(y - 0 + counter*8)


#include <boost/preprocessor/arithmetic/add.hpp>
#include <boost/preprocessor/arithmetic/mul.hpp>
#include <boost/preprocessor/arithmetic/sub.hpp>
#include <boost/preprocessor/repetition.hpp>
#include <boost/preprocessor/iteration/local.hpp>
#include <boost/preprocessor/comparison/equal.hpp>
#include <boost/preprocessor/stringize.hpp>
#include <boost/utility/enable_if.hpp>


namespace vli{
    namespace detail{


/* \cond I do not need this part in the doc*/


#define VLI_EIGHT_MULTIPLY(n)    BOOST_PP_STRINGIZE(BOOST_PP_MUL(n,8))

#define VLI_SUBTRACTION( z, n, unused) "ld %[tmp_register1],"VLI_EIGHT_MULTIPLY(n)"(%[x])   \n\t" \
                                       "ld %[tmp_register2],"VLI_EIGHT_MULTIPLY(n)"(%[y])   \n\t" \
                                        BOOST_PP_IF(n,BOOST_PP_STRINGIZE(subfe),BOOST_PP_STRINGIZE(subfc))" %[tmp_register1], %[tmp_register2] , %[tmp_register1] \n\t" \
                                       "std %[tmp_register1],"VLI_EIGHT_MULTIPLY(n)"(%[x])  \n\t" \

#define VLI_SUBTRACTION3( z, n, unused) "ld %[tmp_register1],"VLI_EIGHT_MULTIPLY(BOOST_PP_ADD(n,1))"(%[x])   \n\t" \
                                        "subfe %[tmp_register1], %4,  %[tmp_register1]\n\t" \
                                        "std %[tmp_register1],"VLI_EIGHT_MULTIPLY(BOOST_PP_ADD(n,1))"(%[x])  \n\t" \

#define VLI_GENERATE_SUBTRACTION(m)  BOOST_PP_REPEAT(BOOST_PP_ADD(m,2), VLI_SUBTRACTION, ~)

#define VLI_GENERATE_SUBTRACTION3(m)  BOOST_PP_REPEAT(BOOST_PP_ADD(m,1), VLI_SUBTRACTION3, ~)

template<std::size_t NumWords, typename range = void>
struct helper_inline_sub;

/**
 \brief addition between two integer<n*128>, n*128 <= 512
 \return void
 \param x boost::uint64_t* pointer of the first entry of the Integer container
 \param y boost::uint64_t* pointer of the first entry of the Integer container
 This operator performs a += between two integer<n*128> The ASM solver is specific 
 and full unroll n belongs to the interval 1 to 8, 128-bit <= vli::integer<n*128>  <= 512-bit
*/
#define FUNCTION_INLINE_sub_nbits_nbits(z, m, unused)                                                  \
template<std::size_t NumWords>                                                                         \
struct helper_inline_sub<NumWords,typename boost::enable_if_c< NumWords == BOOST_PP_ADD(m,2)>::type>{  \
    static void inline inline_sub(boost::uint64_t* x, boost::uint64_t const* y){                       \
        boost::uint64_t tmp_register1, tmp_register2;                                                  \
        __asm__ __volatile__ (                                                                         \
            VLI_GENERATE_SUBTRACTION(m)                                                                   \
        : [tmp_register1] "=&r" (tmp_register1), [tmp_register2] "=&r" (tmp_register2)                  \
        : [x] "b" (x), [y] "b" (y)                                                                     \
        : "memory", "cc");                                                                             \
    };                                                                                                 \
                                                                                                       \
    static void inline_sub(boost::uint64_t* x, boost::int64_t const y){                                \
        boost::uint64_t tmp_register1, tmp_register2;                                                  \
        boost::uint64_t constant(y >> 63);                                                             \
        __asm__ __volatile__ (                                                                         \
            "ld %[tmp_register1],     0(%[x])      \n\t"                                               \
            "subc  %[tmp_register1],  %[tmp_register1], %3 \n\t"                                       \
            "std %[tmp_register1],   0(%[x])  \n\t"                                                    \
            VLI_GENERATE_SUBTRACTION3(m)                                                                  \
        : [tmp_register1] "=&r" (tmp_register1), [tmp_register2] "=r" (tmp_register2)                  \
        : [x] "b" (x), "r" (y), "r" (constant)                                                         \
        : "memory", "cc");                                                                             \
    };                                                                                                 \
};                                                                                                     \

BOOST_PP_REPEAT(7, FUNCTION_INLINE_sub_nbits_nbits, ~) //unroll until 512, maybe test 1024

#undef FUNCTION_INLINE_sub_nbits_nbits

#undef VLI_EIGHT_MULTIPLY
#undef VLI_SUBTRACTION
#undef VLI_SUBTRACTION3

    }} // end namespace
#endif
